name: Check code quality
run-name: Check code quality with detekt
on: [ push ]
jobs:
  Detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Detekt
        shell: bash
        run: ./gradlew detekt