name: Check code quality
run-name: Check code quality with detekt
on: [ push ]
jobs:
  Detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          cache-disabled: true

      - name: Detekt
        shell: bash
        run: ./gradlew detekt